### ISSUE TITLE
New feature request - move to name `sys.scripts`

### ISSUE THREAD

**Issue by jacebenson** [thewhitespace/Xplore#24]
Not sure if you're willing to make a change like this so I'll make an issue and we can figure it out.  The change is rather small.

I type sys.scripts.do and use the `Background - Scripts` more often then I care to.  However if the processor had a name of `sys.scripts` instead of `snd_xplore` then this would not be an issue.  Is this something you would accept in a PR?

**Comment by jacebenson** [comment]
![image](https://user-images.githubusercontent.com/638764/63600912-129dc900-c58a-11e9-9932-df2e4469de7a.png)

**Comment by jneale** [comment]
Hey Jace, neat idea but I think you just need to adjust your muscle memory and click the glasses on the top right instead! ;)

The main reason I'm going to reject this though is because Xplore works differently to background scripts and it is occasionally useful to use the real background scripts page - losing it entirely would be bad.

I could possibly add another processor called `sys.scripts` which is simply a redirect to Xplore and that way you could turn on/off as you like. Would that be a good enough solution?

**Comment by jacebenson** [comment]
Nah, if there's a reason to keep the old `sys.scripts.do` then i say leave it.  

I'll just have to try to remember to use xplore when i have it.
